wordpress_sites:
  production:
    site_hosts:
      - canonical: njordsol.dk
        redirects:
          - www.njordsol.dk
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@bitbucket.org:molamil/622-com-danish-tm.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: true
    env:
      db_name: AYUXfacZ
      wp_env: production

  staging:
    site_hosts:
      - canonical: njordsol.staging.spellio.com
        redirects:
          - www.njordsol.staging.spellio.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@bitbucket.org:molamil/622-com-danish-tm.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: staging 
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    env:
      db_name: TVCfEsRW
      wp_env: production
